
name: Publish Spylgass Improvements to CurseForge and Modrinth

on:
  workflow_dispatch:
    inputs:
      curseforge:
        default: true
        description: 'Publish in curseforge'
        type: boolean
      modrinth:
        default: true
        description: 'Publish in modrinth'
        type: boolean
      fabric:
        default: true
        description: 'Publish in fabric version'
        type: boolean
      neoforge:
        default: true
        description: 'Publish in neoforge version'
        type: boolean
      minecraftVersion:
        description: 'Minecraft Version. Ex: [1.20.2,1.21)'
        default: '[1.21,1.22)'
        required: true
      minecraftBaseVersion:
        description: 'Minecraft Base Version. Ex: 1.20.2'
        default: '1.21'
        required: true
      javaVersion:
        required: true
        default: 21
        type: number
      modVersion:
        required: true
        default: '1.5.6'
        description: 'Mod version string. Ex: 1.5'
        type: string
      releaseName:
        required: true
        default: 'Spyglass Improvements'
        description: 'Mod publish name. Ex: Spyglass Improvements'
        type: string

env:
  MINECRAFT_VERSION: ${{ inputs.minecraftVersion }}
  MINECRAFT_BASE_VERSION: ${{ inputs.minecraftBaseVersion }}
  JAVA_VERSION: ${{ inputs.javaVersion }}
  VERSION: ${{ inputs.modVersion }}
  RELEASE_NAME: ${{ inputs.releaseName }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "${{env.JAVA_VERSION}}"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish neoforge (CurseForge)
        if: ${{ inputs.curseforge && inputs.neoforge}}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 571264
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          files: neoforge/build/libs/!(*-dev-shadow|*-sources).jar

          name: "[NeoForge ${{env.MINECRAFT_BASE_VERSION}}] ${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}+mc${{env.MINECRAFT_BASE_VERSION}}+neoforge"
          version-type: release
          changelog-file: changelog.md
          dependencies: |
            curios(optional)

          loaders: "neoforge"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Publish fabric (CurseForge)
        if: ${{ inputs.curseforge && inputs.fabric}}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 571264
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          files: fabric/build/libs/!(*-dev-shadow|*-sources).jar

          name: "[Fabric ${{env.MINECRAFT_BASE_VERSION}}] ${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}+mc${{env.MINECRAFT_BASE_VERSION}}+fabric"
          version-type: release
          changelog-file: changelog.md
          dependencies: |
            trinkets(optional)

          loaders: "fabric"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Publish NeoForge (Modrinth)
        if: ${{ inputs.modrinth && inputs.neoforge }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Z6ykjRlM
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true

          files: neoforge/build/libs/!(*-dev-shadow|*-sources).jar

          name: "[NeoForge ${{env.MINECRAFT_BASE_VERSION}}] ${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}+mc${{env.MINECRAFT_BASE_VERSION}}+neoforge"
          version-type: release
          changelog-file: changelog.md
          dependencies: |
            curios(optional)

          loaders: "neoforge"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Publish Fabric (Modrinth)
        if: ${{ inputs.modrinth && inputs.fabric }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Z6ykjRlM
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true

          files: fabric/build/libs/!(*-dev-shadow|*-sources).jar

          name: "[Fabric ${{env.MINECRAFT_BASE_VERSION}}] ${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}+mc${{env.MINECRAFT_BASE_VERSION}}+fabric"
          version-type: release
          changelog-file: changelog.md
          dependencies: |
            trinkets(optional)

          loaders: "fabric"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
